### ISSUE TITLE
Support for  Eurochron EFWS2900

### ISSUE THREAD

**Issue by latzi0710** [phifogg/ioBroker.sainlogic#11]
Hi Daniel!

Anbei die Daten des traffic für die Wetterstation, mein Handy hat die IP 10.0.0.26, die Wetterstation 10.0.0.35. Man erkennt gut die Kommunikation mit meinem Raspi (10.0.0.210) und WU. Ich hab im WS View den custom port editiert (Leerzeichen dazu und wieder weg); also keine Änderung. Die angehängte Datei hab ich um ".txt" erweitert, damit der upload klappt.
Ich bin gespannt, ob du was rausfindest!

Vielen Dank für deine Mühe!

LG Latzi
[Wetterstation_Traffic.pcap.txt](https://github.com/phifogg/ioBroker.sainlogic/files/4564019/Wetterstation_Traffic.pcap.txt)

**Comment by phifogg** [comment]
Kannst du mir den genauen Typ der Wetterstation noch hier eintragen? Und welche Werte gerade angezeigt werden in der App (Temperatur, Windstärke...). Irgendwas davon dass ich mal suchen kann.

**Comment by phifogg** [comment]
Werte passt, sind ja die Weatherundergrund updates drin :D 
Irgendwie ist aber wenig Kommunikation mit dem Handy - zumindest geht wenig von der Wetterstation zum Handy.

**Comment by phifogg** [comment]
Hehe... deine Wetterstation redet neben WU auch mit irgendjemand in China:
https://whatismyipaddress.com/ip/47.102.253.116
Das würde ich ihr mal verbieten.

**Comment by latzi0710** [comment]
Das ist Ecowitt

**Comment by phifogg** [comment]
Ich sehe einige Befehle die von Handy zu der WS gehen, aber leider keine Daten zurück kommen :/ Sorry.

**Comment by phifogg** [comment]
Da die WS leider nicht auf die Scheduler Befehle reagiert kann ich da keine Daten auslesen. Sorry.
