### ISSUE TITLE
Scheduler received data for unkown command 89 subcommand 95

### ISSUE THREAD

**Issue by heckmic** [phifogg/ioBroker.sainlogic#127]
I use Froggit DP1500 Wi-Fi Wetterserver USB-Dongle & WH3000SE All-in-One. 
I get the Important values from it in iobroker, but I see a lot of errors from this Adapter:

sainlogic.0 | 2022-06-20 08:14:34.667 | error | Scheduler received data for unkown command 89 subcommand 95
sainlogic.0 | 2022-06-20 08:14:34.657 | error | Scheduler received data for unkown command 89 subcommand 95
sainlogic.0 | 2022-06-20 08:14:34.647 | error | Scheduler received data for unkown command 89 subcommand 95
sainlogic.0 | 2022-06-20 08:14:34.637 | error | Scheduler received data for unkown command 89 subcommand 95
sainlogic.0 | 2022-06-20 08:14:34.628 | error | Scheduler received data for unkown command 80 subcommand 71

**Versions:**  
 - Adapter version: 0.9.0
 - JS-Controller version: 4.0.23
 - javascript: v5.7.0
 - Node version: v14.19.2
 - Operating system: debian "buster"

**Comment by phifogg** [comment]
Hm.. that means your station does react differently to other stations. On the scheduler runs I do receive other data than expected. As I have no such station and no documentation it is hard to implement a change for it.
Listener mode should work fine though.
