### ISSUE TITLE
[Dokumentation] small corrections to custom settings parameters

### ISSUE THREAD

**Issue by mcm1957** [phifogg/ioBroker.sainlogic#130]
I've connected a Eurochron EFWS2900 (Conrad) to this adapter.
I suggest the following extensions (or correctsion) to the documentation:

a) When using Upload Customized with Protocol Wunderground the fields Station Id and Station Key must not be empty. I did not receive any data at ioBroker as long as those fields have been empty. Any input is OK as the values are not used by the adapter. Adapter docu states that thea are optional

b) The path inside ws-view app must end with a questionmark (/weatherstation/updateweatherstation.php?) while the path addad as paramater to the adpater doesn mot need the questaion mark. Adapter docu states that they should be identical. if the questionmark is missing at ws-view a warning is logged:

Listener received illegal request: /weatherstation/updateweatherstation.phpID=id&PASSWORD=key&indoortempf=79.2&temp....

**Comment by mcm1957** [comment]
#126 relates to paragraph b) of this issue

**Comment by phifogg** [comment]
Readme updated.

**Comment by mcm1957** [comment]
Thanks
