### ISSUE TITLE
Solar radtion is 0 if sainlogic is set to W/m2

### ISSUE THREAD

**Issue by bw1faeh0** [phifogg/ioBroker.sainlogic#144]
**Describe the bug**  
If I configure sainlogic to use `W/m2` instead of `lx` for the solar radiation, the object value is always set to 0.
When set to `W/m2` the log tells `Target for solarradiation unit is set: W/m2, using conversion: roundTo(x / 126.7, 1)` **every time** data arrives from the weather station.

**To Reproduce**  
1. Go to instance settings of sainloigc
2. Click on 'device settings'
3. Set solar radiation to 'W/m2'

**Expected behavior**  
correct calculation

**Versions:**  
 - Adapter version: v0.10
 - JS-Controller version: 4.0.23
 - Node version: 16.19.0
 - Operating system: debian

Output, if set to `lx`:
![image](https://user-images.githubusercontent.com/29235332/213126408-838b0f83-a203-4fcb-bbc2-69927b80f3a8.png)

Output, if set to `W/m2`:
![image](https://user-images.githubusercontent.com/29235332/213127093-d61ab047-2096-4f09-b968-837b0c698a4b.png)

**Comment by oelison** [comment]
I had the same issue. Push the edit button and set the unit to W/m2. It is cyclicly calling the checkUnit function and divide it to zero and stops then. I think the function need to set the unit of the state correct and then this will disapear also on such change.

**Comment by phifogg** [comment]
Added to release 0.10.1
