### ISSUE TITLE
dnt WeatherScreen Pro

### ISSUE THREAD

**Issue by RasputinBerry** [phifogg/ioBroker.sainlogic#150]
Hallo phifogg,

o.g. Wetterstation ist in der Adapter Beschreibung nicht aufgeführt ... Ich habe trotzdem versucht sie einzubinden. 
Sie wird erkannt und die Datenpunkte werden auch erstellt aber sie bleiben leer.
Wird sie wirklich nicht unterstützt oder muss man bei den Einstellungen etwas "besonderes" beachten ?
(Ich habe unter "ZEITPLANEINSTELLUNGEN" die IP, das Intervall=30 eingetragen, Häkchen "Aktiv" gesetzt ... sonst nix)

Im Protokoll kommt das:

![grafik](https://user-images.githubusercontent.com/56359831/222791456-9bf96bb1-b316-4de3-85d9-ce23a35b83be.png)

Danke für die Erleuchtung, Grüße.

**Comment by RasputinBerry** [comment]
EDIT:

Ich habe mich jetzt "eingelesen" und den Listener mode (mit div. Einstellungen try&error) konfiguriert ... jetzt sehe ich aktuelle Daten ...

**Comment by phifogg** [comment]
Super, danke für das Update. Das wäre auch meine Empfehlung gewesen. 
Um im Scheduler mode mit der Station zu reden muss ich deren API kennen. Da gibt es von den wenigsten Herstellern eine öffentliche Doku,
