### ISSUE TITLE
Lightning

### ISSUE THREAD

**Issue by Michel83** [phifogg/ioBroker.sainlogic#151]
Hello,
is it possible to output the lightning_num and lightning as an object. They will be apparentlyed received.

`2023-03-18 17:05:10.477  - debug:  sainlogic.0 (26466) Listener received EW update:  "stationtype":"WH2650A_V1.7.6","runtime":"762631","dateutc":"2023-03-18   16:05:09","tempinf":"66.74","humidityin":"45","baromrelin":"31.943","baromabsin":"29.379","tempf":"62.06","humidity":"54","winddir":"183","windspeedmph":"0.00","windgustmph":"0.00","maxdailygust":"8.05","solarradiation":"59.82","uv":"0","rainratein":"0.000","eventrainin":"0.161","hourlyrainin":"0.000","dailyrainin":"0.161","weeklyrainin":"0.480","monthlyrainin":"2.591","yearlyrainin":"8.071","totalrainin":"8.071","temp1f":"60.98","humidity1":"56","temp2f":"51.08","humidity2":"74","soilmoisture1":"0","lightning_num":"1","lightning":"31","lightning_time":"1679135954","wh65batt":"0","wh25batt":"0","batt1":"0","batt2":"0","soilbatt1":"1.3","wh57batt":"5","freq":"868M","model":"WH2650A"}`

Greetings

**Comment by phifogg** [comment]
Added since june 6th. 
#129
