### ISSUE TITLE
Battery Status HP1000SE-PRO, external Sensors

### ISSUE THREAD

**Issue by Matzebhv** [phifogg/ioBroker.sainlogic#153]
At this moment only 3 external Sensors have battery status available. 
![sensors](https://user-images.githubusercontent.com/20025244/228677119-7de00b16-9526-48a6-a8bd-291e52757f52.png)
Modern weather stations can connect a bunch of external sensors. In my case:

&wh80batt=3.14&wh40batt=1.6&wh25batt=0

Can you enable battery status for current ecowitt sensors?

Matze

**Comment by phifogg** [comment]
Added to release 0.10.1
