### ISSUE TITLE
Forwarding does not work

### ISSUE THREAD

**Issue by tomschlde** [phifogg/ioBroker.sainlogic#154]
Hi all, i configured the Ecowitt-Station to send the data to IP-Symcon.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/59179041/229835083-3be16c7f-c0c0-4c46-8431-0b378295dc20.png">
this works fine.
Then i configured the Ecowitt Station to send Data to the IObroker.
<img width="472" alt="image" src="https://user-images.githubusercontent.com/59179041/229835484-3f6600d5-74be-450c-b56b-d519ba27082f.png">
this works also fine.

Then the data should be forwarded in the IOBroker to IP-Symcon (url from above).
<img width="476" alt="image" src="https://user-images.githubusercontent.com/59179041/229835917-b9e82e1d-b80f-4b2e-8490-246b69d50800.png">
No Data is sent to IP-Symcon.
The sainlogic adapter logs (silly)  shows no attempts to send data to IP-Symcon.

In the IP-Symcon logs is also no entry from any data from sainlogic to IP-Symcon.

The manual test with the url : http://192.168.1.150:3777/hook/froggit in the browser shows a protocol in the target-system.
<img width="421" alt="image" src="https://user-images.githubusercontent.com/59179041/229837124-07390217-4430-4840-8cb6-b63f439ed3db.png">
so the url in common should be OK.

Seems, that the forwardinfg url is not even called by the sainlogic-Adapter.

**Comment by phifogg** [comment]
Duplicate to #143
