### ISSUE TITLE
Feature Request: Unused DataPoints

### ISSUE THREAD

**Issue by EvilEls** [phifogg/ioBroker.sainlogic#155]
Hi,
currently the adapter creates a default set of datapoints, even though the weatherstation does not support them.
For my WS3500 roughly half of the created DPs are not used, showing NULL.

Please only create DPs if there is actually data to import - or auto remove DPs still showing NULL after x data imports.

Thanks

**Comment by phifogg** [comment]
Good point, this will take some rework on the logic to know which data ports are required or not.

**Comment by phifogg** [comment]
Version 0.11.1 will only create needed data points.
If you want to test, install via guthub from deb branch:
https://github.com/phifogg/ioBroker.sainlogic/tree/dev

Delete all states from sainlogic, start adapter. It will only create the info states at startup, all others as data is recieved.

**Comment by phifogg** [comment]
Available as now on master branch v 0.11.1
