### ISSUE TITLE
String expected, number delivered

### ISSUE THREAD

**Issue by Nackensteak** [phifogg/ioBroker.sainlogic#156]
Hi, 
ich bin neu im IOBroker und dem ganzen Kram, denke aber ich habe einen Bug gefunden.
Ich habe die WS3500 Sainlogic Station seit ein paar Tagen im Einsatz mit der neusten Firmware 2.0.38
Außerdem den aktuellen Adapter 0.10.0
Die Station an sich funktioniert, das Display zeigt alles an.

Ich bekomme aber einfach keine Daten in den IOBroker
Ich habe Ecowitt sowie Wunderground versucht.
Ich habe den Pfad mit und ohne "?" versucht. 
Ich habe die IP 0.0.0.0 oder direkt die vom Broker versucht.
Ich habe den Adapter bereits einmal gelöscht und wieder installiert. 

Es sieht aus als kommen Daten-Updates jede Minute, aber alle Werte sind "null".
![image](https://user-images.githubusercontent.com/130070910/230403577-472cf575-0d59-454a-bb24-40c3d4c5d8e8.png)

Ich erhalte folgenden Log:
sainlogic.0 | 12719 | 2023-04-06 15:58:17.845 | warn | This object will not be created in future versions. Please report this to the developer.
sainlogic.0 | 12719 | 2023-04-06 15:58:17.844 | warn | Object sainlogic.0.info.last_listener_update is invalid: Default value has to be type "string" but receive

![image](https://user-images.githubusercontent.com/130070910/230403056-7fbc0277-8f71-4749-b6fb-17581702fe4d.png)
![image](https://user-images.githubusercontent.com/130070910/230403130-0688993a-5ca8-419b-b77e-f0c67003e67e.png)

Für Hilfe und Tips wäre ich dankbar. 
Ich verwende eine proxmox installation mit IOBroker im LXC. Läuft alles seit ein paar Wochen. Alles andere ohne Probleme.

**Comment by phifogg** [comment]
Bei Server-IP in der EasyWeather-App solltest Du den Port 8081 weglassen. Hier muss nur die IP des IOBroker hosts rein.

**Comment by Nackensteak** [comment]
Danke, probiere ich aus! Weil da IP/Host stand dachte ich der Port ist gemeint. Gruß, Sascha--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 07.04.23, 10:26 schrieb "Daniel Dräs" ***@***.***>:

   
  Bei Server-IP in der EasyWeather-App solltest Du den Port 8081 weglassen. Hier muss nur die IP des IOBroker hosts rein.

**Comment by Nackensteak** [comment]
Mit Ecowitt hab ich es jetzt zum laufe bekommen, danke. --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 07.04.23, 10:26 schrieb "Daniel Dräs" ***@***.***>:

   
  Bei Server-IP in der EasyWeather-App solltest Du den Port 8081 weglassen. Hier muss nur die IP des IOBroker hosts rein.

**Comment by phifogg** [comment]
Closed - working.
