### ISSUE TITLE
Additional Fields for Ecowitt Sensors WN32 and WH31

### ISSUE THREAD

**Issue by Gwenselah** [phifogg/ioBroker.sainlogic#163]
Hello,

the log says:
No mapping found for dataelement: wh26batt
No mapping found for dataelement: batt1

I'm ussing two sensors, a WN32 and  WH31.

Could you please add these two dataelement to the adapter.

kind regards
Andy

**Comment by phifogg** [comment]
Sure, I can look at this.

**Comment by Gwenselah** [comment]
Hello,

I updatet to version 0.10.3. But I still could not see any data points under objects for the new states.
I am missing some thing?

kind regards

**Comment by phifogg** [comment]
Weird... maybe ioB doesn't like to states with the same name. I changed that. Let's try again.

**Comment by phifogg** [comment]
Closed with 0.10.5 (verified on local instance)
