### ISSUE TITLE
[DOCU] add info about forwarning URL

### ISSUE THREAD

**Issue by mcm1957** [phifogg/ioBroker.sainlogic#169]
When forwarding data to weatherundergrount the follwoing url seems to work:

https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?

Please add this information somewhere at config description as the ending "?" seems to make the trick but is not really intuitive.

In addition consider adding a note, that the id and the key are forwarded as transmitted by the device. I was lokking some time whare to enter this info when forwarding.

**Comment by phifogg** [comment]
Added a note to the readme.
