### ISSUE TITLE
greater than max "1500"  </html>*Describe the bug**  

### ISSUE THREAD

**Issue by lhoem** [phifogg/ioBroker.sainlogic#185]
Halo.

folgende Meldung kommt seit 1 oder 2 Tagen bei mir im Protokoll:

State value to set for "sainlogic.0.weather.current.yearlyrain" has value "1558.5" greater than max "1500"

Es regnet halt bei uns seit Tagen.. vielleicht kann man den max bei dem nächsten Update erhöhen...

Installierte Version:
0.11.1
Gruß
lhoem

**Comment by phifogg** [comment]
Ja, sicher, kann ich erhöhen :D Verrücktes Wetter.
Zwischenzeitlich kannst Du den Max-Wert selbst einstellen. Der Datenpunkt wird per-se nicht zur Laufzeit angepasst wenn er schon da ist.

**Comment by phifogg** [comment]
Updated in version 0.11.3
