### ISSUE TITLE
Any advice on adding a WS0835? WS viewer doesn't work.

### ISSUE THREAD

**Issue by kylepyke** [phifogg/ioBroker.sainlogic#187]
Some models of Sainlogic weather stations do not appear to have a way to access sensor data locally. All data collected by the base station is uploaded directly to Weather Underground, without any options to push to a local server.

I have a WS0835, and it appears to be such a device. Do you have any advice for accessing sensor data from the base station?

**Comment by phifogg** [comment]
Unfortunately not, sorry. As long as there is no documented API for this station it is almost impossible to develop an adapter for it.
