### ISSUE TITLE
Reset of the yearly rain did not work

### ISSUE THREAD

**Issue by Trapper12** [phifogg/ioBroker.sainlogic#189]
[@fogg](https://forum.iobroker.net/uid/26685)

Hallo Fogg,

habe die elv WS980wifi. Empfängt auch alle Daten.
Aber zum Jahreswechsel wurden die alten Tages/Wochen/Monats und Jahreswerte beibehalten.
Also nichts auf null gestellt. Adapter 0.10.5

Muss ich da noch irgendwo etwas enstellen?

Gruß und frohes neues Jahr
KLaus

**Comment by phifogg** [comment]
Hallo Klaus,
der Adapter zeigt nur die Werte an die von der Station kommen. Er hat keine Logik um Wochen-/Monats- oder Jahreswerte zu berechnen. Das muss alles direkt aus der Station kommen.
Gruss
Daniel
