### ISSUE TITLE
Future request: iobroker object "soilttemp"

### ISSUE THREAD

**Issue by GameWatchProjects** [phifogg/ioBroker.sainlogic#193]
The objekt "soilmoisture" is given, but the object for soil temperature is in iobroker missing. When the object for soil temperature is already build in, then it will not create in iobroker ...

**Comment by phifogg** [comment]
Hi, can you give me debug log output so I can see that the attrribute should look like?

**Comment by GameWatchProjects** [comment]
Hi, but sorry that I can't give you a debug log, while I've removed the adapter few weeks after no response of my thread. 

So at this time a use weewx on the same machine as iobroker to with the MQTT function, so become real time data from my weather station to iobroker.
