### ISSUE TITLE
2024-06-28 12:04:13.353  - warn: sainlogic.0 (288267) State value to set for "sainlogic.0.weather.current.yearlyrain" has value "2629.9" greater than max "2000"

### ISSUE THREAD

**Issue by Grothesk242** [phifogg/ioBroker.sainlogic#201]
Log is flooded with messages:

```
2024-06-28 12:04:13.353  - warn: sainlogic.0 (288267) State value to set for "sainlogic.0.weather.current.yearlyrain" has value "2629.9" greater than max "2000"
```
Can the range be extended?

**Comment by phifogg** [comment]
Published 0.11.4 with a fix on this to NPM

**Comment by manuxi** [comment]
On mine it states regulary 'State value to set for "sainlogic.0.weather.current.yearlyrain" has value "-253974.6" less than min "0"'

**Comment by phifogg** [comment]
I have seen that before. seems your weatherstation @manuxi  is reporting bogus values.
