### ISSUE TITLE
Only create datapoints which are supported by the weather station

### ISSUE THREAD

**Issue by adx-git** [phifogg/ioBroker.sainlogic#47]
While using "ecowitt" as protocol for my weather station I recognized that some datapoints are created even if there is no string defined for this datapoint.
For example UVraw and dewpointtemp.
The fastest, to implement, solution would be to check if there is a string definition for the protocol and if not, do not create the datapoint.
Since some weather stations might support different datapoints, even if the protocol is the same, the better solution would be an automatic detection and giving the user the possibility to select the desired datapoints.
A mid term solution could be to pre-define datapoint for known weather stations and fall back to default if the station is not recognized.

**Comment by phifogg** [comment]
I believe a first version was part of you pull request. I like the idea of marking the data points for validity of specific weather stations. need to think about it...

**Comment by phifogg** [comment]
I blieve this is added quite some time by now. Closing issue.
