### ISSUE TITLE
Zusätzliche Daten Sonnenaufgang-/untergang Mondphasen usw. ELV 980WIFI aus Box holen möglich?

### ISSUE THREAD

**Issue by Nachgefragt** [phifogg/ioBroker.sainlogic#62]
Hallo Daniel, 

ich hab gesehen das Sonnenaufgang/untergang, Mondphasen im Display der Station angezeigt werden kann man diese Daten auch auslesen?

Gruß
Norbert

**Comment by phifogg** [comment]
Leider nein, die kommen nicht mit der API raus.
Ich denke aber mal die wären relativ leicht aus den GEO Koordinaten bestimmbar die ioBroker ja hat.
