### ISSUE TITLE
Version 0.6.6 wird nicht installiert

### ISSUE THREAD

**Issue by F95Markus** [phifogg/ioBroker.sainlogic#71]
Hallo,
ich habe leider das Problem das ich den Adapter nicht updaten kann. 

Anbei hab ich die beiden Logdatein
![IOBrokerLOG Sainlogic](https://user-images.githubusercontent.com/83089268/115911879-f218c700-a46e-11eb-9471-7a959abde5cb.jpg)
![Log Sainlogic](https://user-images.githubusercontent.com/83089268/115911902-f9d86b80-a46e-11eb-8d37-c5e4976e2fc2.jpg)

Ich hoffe ihr könnt mir helfen. Soweit läuft der Adapter mit meiner Froggit WH3000 sehr gut mittlerweile.

**Comment by phifogg** [comment]
Das ist komisch, die 0.6.6 gibt es sehr wohl:
https://github.com/phifogg/ioBroker.sainlogic/releases/tag/0.6.6

Welche Version hast Du aktuell drauf?

**Comment by F95Markus** [comment]
Aktuell ist die 0.6.0 installiert und bekomme auch keine höhere installiert. Da ist dann das selbe Problem.

**Comment by olafbono** [comment]
Ich hatte das gleiche Problem, 0.6.6 wird von npm nicht gefunden.

Workaround: Auf der Shell einloggen als user iobroker, dann Version 0.6.6 als Archiv runterladen (z.B. wget https://github.com/phifogg/ioBroker.sainlogic/archive/refs/tags/0.6.6.tar.gz), dann aus dem Archiv installieren:

npm install 0.6.6.tar.gz --prefix "/srv/iobroker"
(oder /opt/iobroker, je nachdem, wo iobroker installiert ist).

**Comment by F95Markus** [comment]
Dankeschön so hat es jetzt geklappt.

**Comment by phifogg** [comment]
Wow... das sollte nicht so sein. Aber schön wenn es geklappt hat. 0.7.0 kommt bald, dann schauen wir mal ob es den Umweg wieder braucht....
