### ISSUE TITLE
adapter installation without  weather station

### ISSUE THREAD

**Issue by volkerz12** [phifogg/ioBroker.sainlogic#96]
At first I had problems with the installation of the Sainlogic adapter. It wasn't until I installed via GITHUB that the installation succeeded. I haven't bought a weather station yet. First I wanted to see if the adapter installation worked. It is unusual for the adapter not to show up in the instances. The adapter appears in the objects. Is this behavior normal for this adapter?

**Comment by phifogg** [comment]
It should appear in instances as well, at least it does for me :D

As fot the installation, I know, trying to get the repo team to accept the latest version, but they added some extra hurdles which take me extra time to figure it out. Will try to work on this during october...

**Comment by volkerz12** [comment]
Thanks for answering. Could the reason for not appearing in  instances, the
fact I have no wether station yet?
What is repo team?


Greetings

Volker Ziegler


Am So., 26. Sept. 2021 um 15:15 Uhr schrieb Daniel Dräs <
***@***.***>:

**Comment by volkerz12** [comment]
Hello,

there is no message in the log.

I have installed the adapter again via github. Please see attached
installing log.


Grreetings

Volker Ziegler


Am Mo., 27. Sept. 2021 um 23:43 Uhr schrieb Daniel Dräs <
***@***.***>:

**Comment by phifogg** [comment]
Hi Volker,
can't see any attachment :/
Daniel

**Comment by volkerz12** [comment]
Hi Daniel,

sorry, here is attachment.

Greetings

Volker Ziegler


Am Mi., 29. Sept. 2021 um 11:29 Uhr schrieb Daniel Dräs <
***@***.***>:

**Comment by phifogg** [comment]
Seems the attachment doesn't carry over to github :/

**Comment by volkerz12** [comment]
sorry I did not understand. Did you get the  attachment ?

Volker Ziegler


Am Mi., 29. Sept. 2021 um 13:31 Uhr schrieb Daniel Dräs <
***@***.***>:

**Comment by phifogg** [comment]
No... seems github does not store the attachment in your email. Can you copy/paste the content?

 29. September 2021 17:09, "volkerz12" ***@***.*** ***@***.******@***.***>)> schrieb:
sorry I did not understand. Did you get the attachment ?

 Volker Ziegler
 Am Mi., 29. Sept. 2021 um 13:31 Uhr schrieb Daniel Dräs <
 ***@***.***>:

**Comment by volkerz12** [comment]
here is it. I hope the words are big enough to read

[image: image.png]
[image: image.png]



Volker Ziegler


Am Mi., 29. Sept. 2021 um 17:31 Uhr schrieb Daniel Dräs <
***@***.***>:

> No... seems github does not store the attachment in your email. Can you
> copy/paste the content?
>
> 29. September 2021 17:09, "volkerz12" ***@***.***

**Comment by phifogg** [comment]
doesn't work either ... sorry. All I see is:
[image: image.png]
[image: image.png]

You can try to answer to this issue on the github website and attache the files/images there.

**Comment by volkerz12** [comment]
Let us try here
[saint.pdf](https://github.com/phifogg/ioBroker.sainlogic/files/7253448/saint.pdf)

**Comment by volkerz12** [comment]
Hello,

I need you help again.

I have bought a Sainlogic Weatherstation WS3500. I want to connect to
iobroker and import the weather data in iobroker. I need temperatur,
pressure, humidity, windspeed, winddirection

Do I have to use Wunderground or ecowitt?


Thanks

Greetings

Volker Ziegler


Am So., 26. Sept. 2021 um 15:15 Uhr schrieb Daniel Dräs <
***@***.***>:

**Comment by phifogg** [comment]
Hi Volker,
good question. Usually the ecowitt has more values it transmits. Would recommend you to test both with debug and see what you get in the logs.

Daniel

**Comment by volkerz12** [comment]
Hi Daniel,

I have tried ecowitt. But in iobroker is no data displayed.

please see attachement.


greetings

Volker Ziegler


Am Mo., 13. Dez. 2021 um 08:43 Uhr schrieb Daniel Dräs <
***@***.***>:

**Comment by volkerz12** [comment]
here is the  attachement

Volker Ziegler


Am Mo., 13. Dez. 2021 um 18:40 Uhr schrieb Familie Ziegler <
***@***.***>:

**Comment by volkerz12** [comment]
HI Daniel,

do you have an answer?

Greetings

Volker


Am Mo., 13. Dez. 2021 um 18:42 Uhr schrieb Familie Ziegler <
***@***.***>:

**Comment by phifogg** [comment]
Hm.. attachment is missing again.

**Comment by volkerz12** [comment]
Hi Daniel,

sorry again. Here is it.

Greetings

Volker


Am Fr., 17. Dez. 2021 um 16:10 Uhr schrieb Daniel Dräs <
***@***.***>:

**Comment by phifogg** [comment]
no, it's not. not sure if it works via email...

**Comment by volkerz12** [comment]
Ok, please try the link below

https://gofile.io/d/qXNNKF

Greetings

Volker Ziegler


Am Mo., 20. Dez. 2021 um 14:41 Uhr schrieb Daniel Dräs <
***@***.***>:

**Comment by volkerz12** [comment]
Did you get the attachment?

https://gofile.io/d/qXNNKF

Greetings

Volker Ziegler


Am Mo., 20. Dez. 2021 um 15:04 Uhr schrieb Familie Ziegler <
***@***.***>:

**Comment by phifogg** [comment]
Yes, link works. thank you.

The protocol-section is only relevant for the listener. This would mean your weatherstation needs to be configured to send it's data to ioBroker. In my station I can do that with WSView and custom setup. Not sure this works for you.

This is how it looks on my WSView settings:
![image](https://user-images.githubusercontent.com/5994342/146967221-0c222848-7d0d-4639-b0c2-2243ed30f2d5.png)

As for the scheduler, it will only be able to pull some information. If you activate debug I might be able to decode it... not fully sure though. So far I was lucky to find a documentation how to parse the content.

**Comment by volkerz12** [comment]
Ok,

thanks for helping. This will not work. I send weatherstatoin  back to
amazon.


Greetings

Volker Ziegler


Am Di., 21. Dez. 2021 um 17:46 Uhr schrieb Daniel Dräs <
***@***.***>:

**Comment by adx-git** [comment]
Which one did you use, might be interesting for other as well.

**Comment by phifogg** [comment]
He mentioned a Sainlogic Weatherstation WS3500 some posts back.

@volkerz12 : Sorry to hear that. Sainlogic has so many of these stations and it seems not all are equal.

Closing this issue for now. Feel free to open a new one when needed.
